# Generated by Django 4.0.2 on 2022-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
    ]
